project:
  type: website
  resources:
    - static/

website:
  title: "A blog by RC"
  navbar:
    background: primary
    search: true
    left:
      - posts/posts.qmd
      - text: "Talks and articles"
        href: publications.qmd
      - about.qmd 

    right:
      - icon: github
        href: https://github.com/rcap107/
      - icon: bluesky
        href: https://bsky.app/profile/riccardocappuzzo.com

  page-footer: |
    <div class="site-footer">
      Copyright 2026, Riccardo Cappuzzo â€” <a href="/disclaimer.qmd">Disclaimer</a>
    </div>
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    include-in-header: _includes/head.html
    toc: true
    toc-expand: true
execute: 
  freeze: auto